spring:
  datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&serverTimezone=UTC   
        username: root 
        password: 
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
                  